### ISSUE TITLE
Audio stops increasing in speed at 1024x (102400%)

### ISSUE THREAD

**Issue by walle303** [joezeng/ytmnd#1]
Most likely the absolute max of Howler.js and/or Chromium

Browser: Chromium Version 49.0.2593.0 (64-bit)

**Comment by joezeng** [comment]
I don't think this one is actually solvable — it's pretty amazing that it can get up to 1024x already via the web audio API; I think it's a software issue beyond the capabilities of Javascript hacks to get it to go any faster.
